In [1]:
import numpy as np


In [2]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [1]:
print(1+2)

3


In [2]:
print(1+2)

3


In [6]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
arr=np.random.randint(0,100,25)

In [14]:
arr

array([26, 77, 74, 51, 36, 63, 34, 42, 79, 72, 57, 90, 26, 33, 89, 97, 93,
       61,  7, 25, 50, 14, 69,  0, 47])

In [19]:
arr.reshape(5,5)

array([[26, 77, 74, 51, 36],
       [63, 34, 42, 79, 72],
       [57, 90, 26, 33, 89],
       [97, 93, 61,  7, 25],
       [50, 14, 69,  0, 47]])

In [17]:
np.random.randn(5)

array([-0.09723571, -0.8564679 ,  0.34498251, -0.48107583, -1.29522792])

In [21]:
arr.max()


97

In [22]:
arr.min()

0

In [23]:
arr(id(97))

TypeError: 'numpy.ndarray' object is not callable

In [24]:
arr.argmax()

15

In [26]:
arr.sort()

In [27]:
arr

array([ 0,  7, 14, 25, 26, 26, 33, 34, 36, 42, 47, 50, 51, 57, 61, 63, 69,
       72, 74, 77, 79, 89, 90, 93, 97])

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr.shape

(25,)

In [30]:
arr[0:5]

array([ 0,  7, 14, 25, 26])

In [31]:
arr[0:5]=99

In [32]:
arr

array([99, 99, 99, 99, 99, 26, 33, 34, 36, 42, 47, 50, 51, 57, 61, 63, 69,
       72, 74, 77, 79, 89, 90, 93, 97])

In [33]:
arr=np.arange(0,11)  

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
list=arr[0:5]

In [41]:
list[:]=5

In [42]:
list

array([5, 5, 5, 5, 5])

In [43]:
arr

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [44]:
lis=arr[4:9].copy()

In [45]:
lis

array([5, 5, 6, 7, 8])

In [48]:
lis[:]=10

In [49]:
arr

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [50]:
arr


array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [61]:
array_1=np.random.randint(0,100,9)

In [62]:
array_1.reshape(3,3)

array([[ 7, 93, 62],
       [ 3, 26, 45],
       [88, 12, 31]])

In [67]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [68]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [79]:
arr=np.arange(0,10)

In [80]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
boolean_arr=arr>5

In [86]:
arr[boolean_arr]

array([6, 7, 8, 9])

In [87]:
arr[arr<3]

array([0, 1, 2])

In [88]:
arr=np.arange(50).reshape(5,10)

In [89]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [91]:
arr[1][2:7]

array([12, 13, 14, 15, 16])

In [99]:
arr[2:4,6:8]

array([[26, 27],
       [36, 37]])

In [107]:
arr=np.arange(0,10)

In [101]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [103]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [105]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [106]:
arr/arr

c:\users\lala\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
np.max(arr)

9

In [109]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [110]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [111]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [112]:
arr.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [113]:
arr.add(100)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [93]:
import numpy as np

In [95]:
import pandas as pd

In [4]:
list=[10,20,30]

In [5]:
list

[10, 20, 30]

In [14]:
labels=['a','b','c']

In [7]:
arr=np.array(list)
d={'a':10,'b':20,'c':30}

In [8]:
arr

array([10, 20, 30])

In [15]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [16]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [18]:
sp=pd.Series([1,2,3],['India','USA','China'])

In [19]:
sp


India    1
USA      2
China    3
dtype: int64

In [20]:
sp[1]

2

In [21]:
sp['USA']

2

In [26]:
 sp1=pd.Series([1,4,5],['India','USA','China'])

In [27]:
sp1

India    1
USA      4
China    5
dtype: int64

In [28]:
sp+sp1

India    2
USA      6
China    8
dtype: int64

In [32]:
df=pd.DataFrame([])


In [30]:
df


Empty DataFrame
Columns: []
Index: []

In [41]:
from numpy.random import randn
np.random.seed(101)

In [42]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])


In [43]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [48]:
df[['W','Z','X']]

W         Z         X
A  2.706850  0.503826  0.628133
B  0.651118  0.605965 -0.319318
C -2.018168 -0.589001  0.740122
D  0.188695  0.955057 -0.758872
E  0.190794  0.683509  1.978757

In [49]:
df['new']=df['W']+df['Z']

In [50]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [57]:
df.drop(['new'],axis=1,inplace=True)

In [58]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
df.drop(['E'])

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752

In [56]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [64]:
df.loc[['A','B'],['X','Z']]

X         Z
A  0.628133  0.503826
B -0.319318  0.605965

In [63]:
df.loc[2]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2] of <class 'int'>

In [65]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [70]:
df[(df['W']>0) | (df['X']>1)][['X','Y']]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [71]:
new='MP UP AP MH Goa'.split()

In [72]:
new


['MP', 'UP', 'AP', 'MH', 'Goa']

In [73]:
df['states']=new

In [74]:
df

W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     MP
B  0.651118 -0.319318 -0.848077  0.605965     UP
C -2.018168  0.740122  0.528813 -0.589001     AP
D  0.188695 -0.758872 -0.933237  0.955057     MH
E  0.190794  1.978757  2.605967  0.683509    Goa

In [77]:
df.set_index('states')

W         X         Y         Z
states                                        
MP      2.706850  0.628133  0.907969  0.503826
UP      0.651118 -0.319318 -0.848077  0.605965
AP     -2.018168  0.740122  0.528813 -0.589001
MH      0.188695 -0.758872 -0.933237  0.955057
Goa     0.190794  1.978757  2.605967  0.683509

In [88]:
df.set_index(ind)

KeyError: 'A'

In [86]:
ind=['A','B','C','D','E']

In [87]:
ind

['A', 'B', 'C', 'D', 'E']

In [103]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [99]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]


In [102]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [101]:
del list

In [104]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [105]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [107]:
 df['A']

G1  1    0.302665
    2   -1.706086
    3   -0.134841
G2  1    0.166905
    2    0.807706
    3    0.638787
Name: A, dtype: float64

In [111]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [113]:
df.index.names=['Group','num']

In [114]:
df

A         B
Group num                    
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [115]:
df.loc['G2'].loc[2]['B']

0.07295967531703869

In [118]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [119]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [120]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [122]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [123]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [127]:
df.fillna(value='Vacant')

A       B  C
0       1       5  1
1       2  Vacant  2
2  Vacant  Vacant  3

In [130]:
df['A'].fillna(value=df['A'].mean(),inline=True)

TypeError: fillna() got an unexpected keyword argument 'inline'

In [129]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [131]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [132]:
df = pd.DataFrame(data)

In [133]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [134]:
by_comp = df.groupby("Company")

In [135]:
by_comp

In [137]:
by_comp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [138]:
by_comp.max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [140]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [141]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [142]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [143]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [144]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [145]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [146]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [150]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [152]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  A0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [153]:
pd.merge(left,right,how='outer',on='key')

key   A   B   C   D
0  K0  A0  B0  A0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

Joining

In [154]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [155]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [1]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [4]:
df['col2'].unique().transpose()

array([444, 555, 666], dtype=int64)

In [5]:
df['col2'].nunique()

3

In [7]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [8]:
df['col1'].apply(lambda x:x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [11]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [12]:
del df['col1']

In [13]:
df


col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [15]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [16]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [21]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [22]:
df.sort_values(['col2'])

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [24]:
import numpy as np
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [26]:
df.dropna(axis=1)

col3
0  abc
1  def
2  ghi
3  xyz

In [27]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [28]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [29]:
import pandas as pd

In [32]:
pd.read_csv('example.csv')

FileNotFoundError: File b'example.csv' does not exist

In [31]:
pwd

'F:\\Udemy\\Python'